---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600
  ignore_errors: yes

- name: Ensure Apache is installed on Debian.
  apt: "name={{ apache_packages }} state={{ apache_packages_state }}"
